import { type NextPage } from "next";
import Head from "next/head";
import { Box, Container, FormControl, Input, Stack } from "@chakra-ui/react";
import { Select } from "chakra-react-select";
import { api } from "~/src/utils/api";

const Home: NextPage = () => {
  const { data } = api.city.getAll.useQuery();

  if (!data) return <div>Loading...</div>;

  const cityOptions = data.map((city) => ({
    value: city.id,
    label: city.id,
  }));

  return (
    <>
      <Head>
        <title>BBM Watcher</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box minH="100vh">
        <Container maxW="container.xl">
          <Stack mt="5">
            <FormControl>
              <Select options={cityOptions} />
            </FormControl>

            <FormControl>
              <Select options={cityOptions} />
            </FormControl>
          </Stack>
        </Container>
      </Box>
    </>
  );
};

export default Home;
