import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
  Container,
} from "@chakra-ui/react";
import { api } from "../utils/api";
import { Text } from "@chakra-ui/react";
import {
  parseDateToIndonesiaDate,
  parseFuelType,
  parsePrice,
} from "../utils/parse";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data } = api.fuels.getByCity.useQuery();

  return (
    <>
      <Head>
        <title>BBM Watcher</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl">
        <TableContainer>
          <Table variant="simple">
            <Thead>
              <Tr>
                <Th>Tipe</Th>
                <Th>Kota</Th>
                <Th>Harga</Th>
                <Th>Tanggal</Th>
              </Tr>
            </Thead>
            <Tbody>
              {data?.map((item) => {
                return (
                  <Tr key={item.id}>
                    <Td>{parseFuelType(item.type)}</Td>
                    <Td>{item.City.id}</Td>
                    <Td>{parseDateToIndonesiaDate(item.date)}</Td>
                    <Td>{parsePrice(item.price)}</Td>
                  </Tr>
                );
              })}
            </Tbody>
          </Table>
        </TableContainer>
      </Container>
    </>
  );
};

export default Home;
